# Generated by Django 2.2.3 on 2019-10-08 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kategori',
            field=models.CharField(choices=[('Jalan', 'jalan'), ('Jembatan', 'jembatan'), ('Lampu Jalan', 'lampu_jalan')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Belum Di Survey', 'belum_di_survey'), ('Sedang Di Survey', 'sedang_di_survey'), ('Telah Di Survey', 'telah_di_survey'), ('Dalam Proses Pengerjaan', 'dalam_proses_pengerjaan'), ('Telah Di Perbaiki', 'telah_di_perbaiki')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
