# Generated by Django 2.2.3 on 2019-10-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191009_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Belum Di Survey', 'belum_di_survey'), ('Sedang Di Survey', 'sedang_di_survey'), ('Telah Di Survey', 'telah_di_survey'), ('Dalam Proses Pengerjaan', 'dalam_proses_pengerjaan'), ('Telah Di Perbaiki', 'telah_di_perbaiki')], default='Belum Di Survey', max_length=255),
        ),
    ]
