# Generated by Django 2.2.3 on 2019-10-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, default='blank.jpg', null=True, upload_to='pengaduan'),
        ),
    ]
