# Generated by Django 2.2.3 on 2019-09-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_p',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
