# Generated by Django 2.2.3 on 2019-09-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_foto_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='foto_p',
            new_name='foto_profil',
        ),
    ]
