# Generated by Django 2.2.3 on 2019-09-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
